config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  filter :locale

  # Override Devise::RegistrationsController so that we can do some custom things.
  devise_for :users, controllers: { registrations: 'registrations' }

  as :user do

    authenticated :user, lambda { |u| u.admin? } do

      namespace :admin_only, path: 'admin' do
        resources :master_checklists
        get  'master-checklists/max-list-position', to: 'master_checklists#max_list_position'
        post 'master-checklists/toggle-in-use', to: 'master_checklists#toggle_in_use'
        post 'master-checklists/set-to-no-longer-used/:id', to: 'master_checklists#set_to_no_longer_used',
             as: :master_checklists_set_to_no_longer_used

        get 'master-checklists/next-onebased-list-position', to: 'master_checklists#next_one_based_list_position'

        get 'payments', to: 'dashboard#payments'

        resources :master_checklist_types

        # Update membership status for all users
        get 'anvandare/update-membership-status-all', to: 'user_account#update_membership_status_all',
            as: :update_membership_status_all

      end


      # UserChecklists - that only an admin do:
      # View all the checklists for a user
      get 'admin/anvandare/:user_id/lista', to: 'user_checklists#index',
          as: 'user_checklists'

      # Export Information (CSV files)
      post 'admin/export-ansokan-csv'
      post 'admin/export-payments-csv'
      put 'admin/export-payments-covering-year-csv'

      # Route for testing Exception Notification configuration
      get "test_exception_notifications" => "application#test_exception_notifications"

      root to: 'shf_applications#index', as: :admin_root

    end
  end

  # ---------------------------------------------------------------------------
  # We're already using 'admin' as the name of a user role, so we
  # use "admin_only" here to avoid colliding with that term with the
  # namespace directories and class names.  We keep 'admin' as the path
  # for simplicity and some consistency.
  # namespace :admin_only, path: 'admin' do
  namespace :admin_only, path: 'admin' do

    resources :member_app_waiting_reasons

    get 'dashboard', to: 'dashboard#index'
    put 'dashboard_timeframe', to: 'dashboard#update_timeframe'

    put 'dashboard_show_recent_activity', to: 'dashboard#show_recent_activity'


    # AppConfiguration is a Singleton.
    # Admins only view and edit the AppConfiguration.
    # There is no need for index or destroy.
    #
    # :id is an optional parameter so that view buttons, etc., work fine
    # with the Rails conventions
    #
    # as: :..app_configuration..  is needed when the id is an optional parameter

    get 'app_configuration(/:id)/redigera', to: 'app_configuration#edit',
        as: :edit_app_configuration

    # must use the as: :put_app_configuration so that the method does not conflict with get 'app_configuration(/:id)' route (#show)
    put 'app_configuration(/:id)', to: 'app_configuration#update', as: :put_app_configuration

    get 'app_configuration(/:id)', to: 'app_configuration#show', as: :app_configuration


    get 'user_profile_edit/:id', to: 'user_profile#edit', as: :user_profile_edit
    put 'user_profile_update/:id', to: 'user_profile#update', as: :user_profile_update
    get 'user_profile_become/:id', to: 'user_profile#become', as: :become_user

    # Edit User Account
    get 'anvandare/:user_id/redigera', to: 'user_account#edit', as: :edit_user_account
    put 'anvandare/:user_id', to: 'user_account#update', as: :user_account

    # Design Guide
    get 'designguide', to: 'design_guide#show'

  end
  # ---------------------------------------------------------------------------

  get '/pages/*id', to: 'pages#show', as: :page, format: false


  scope(path_names: { new: 'ny', edit: 'redigera' }) do
    resources :business_categories, path: 'kategori' do
      get :get_edit_row, on: :member
      get :get_display_row, on: :member
    end

    resources :shf_applications, path: 'ansokan' do
      member do
        put 'remove_attachment'

        put 'update-reason-waiting', to: 'shf_applications#update_reason_waiting',
            as: 'reason_waiting'

        get 'start-review', to: 'shf_applications#show'
        post 'start-review', to: 'shf_applications#start_review'

        get 'accept', to: 'shf_applications#show'
        post 'accept', to: 'shf_applications#accept'
        get 'reject', to: 'shf_applications#show'
        post 'reject', to: 'shf_applications#reject'
        get 'need-info', to: 'shf_applications#show'
        post 'need-info', to: 'shf_applications#need_info'
        get 'cancel-need-info', to: 'shf_applications#show'
        post 'cancel-need-info', to: 'shf_applications#cancel_need_info'
        get 'need-payment', to: 'shf_applications#show'
        post 'need-payment', to: 'shf_applications#need_payment'
        get 'cancel-need-payment', to: 'shf_applications#show'
        post 'cancel-need-payment', to: 'shf_applications#cancel_need_payment'
        get 'received-payment', to: 'shf_applications#show'
        post 'received-payment', to: 'shf_applications#received_payment'

        get 'get_edit_row_business_category'
        get 'get_display_row_business_category'

        put 'business_subcategories'
      end

    end

    resources :companies, path: 'hundforetag' do
      member do
        put 'edit_payment', to: 'companies#edit_payment', as: 'edit_payment'
        post 'fetch_from_dinkurs', to: 'companies#fetch_from_dinkurs', as: 'fetch_from_dinkurs'
      end
    end


    # User Account.  Only admins can edit (see the route above for /admin)
    # Note that this sets the default id parameter to :user_id (instead of just :id)
    resources :users, path: 'anvandare', except: [:edit, :update]  do

      # this will add an :id parameter
      member do
        put 'edit_status', to: 'users#edit_status', as: 'edit_status'

        # User Payment Receipts
        get 'betalning-kvitton', to: 'users#view_payment_receipts',
            as: 'view_payment_receipts'
        get 'betalning-kvitton-ladda-ner', to: 'users#download_payment_receipts_pdf',
            as: 'download_payment_receipts_pdf'
      end

      post 'toggle_membership_package_sent', to: 'users#toggle_membership_package_sent'

      # ---------------------------------------------------
      # UserChecklist as a nested resource under User, with path '/lista' in the URI
      resources :user_checklists, only: [:show], path: 'lista' do
        get 'progress', to: 'user_checklists#show_progress'
      end


      # ---------------------------------------------------
      # Uploaded files

      # Do these 2 routes manually so that we can add the optional parameter :from_acct_pg
      # They must go before the resources :uploaded_files... statement below so that
      #  /anvandare/:user_id/filer/ny is matched to the request before
      #  /anvandare/:user_id/filer/:id  otherwise the router will think that :id = 'ny'
      #
      get 'filer/ny(/:from_acct_pg)', to: 'uploaded_files#new',
          as: 'new_uploaded_file'
      post 'filer/(/:from_acct_pg)', to: 'uploaded_files#create'

      # UploadedFile as a nested resource under User, with page '/filer' in the URI
      resources :uploaded_files, path: 'filer', except: [:new, :create]

    end

    # UserChecklists
    post 'anvandare/lista/all_changed_by_completion_toggle/:id', to: 'user_checklists#all_changed_by_completion_toggle',
         as: 'user_checklist_all_changed_by_completion_toggle'
    post 'anvandare/lista/set-all-completed/:id', to: 'user_checklists#set_complete_including_kids',
         as: 'user_checklist_set_complete_including_kids'
    post 'anvandare/lista/set-all-uncompleted/:id', to: 'user_checklists#set_uncomplete_including_kids',
         as: 'user_checklist_set_uncomplete_including_kids'


    get 'anvandare/:id/proof_of_membership', to: 'users#proof_of_membership',
        as: 'proof_of_membership'

    get 'hundforetag/:id/company_h_brand', to: 'companies#company_h_brand',
        as: 'company_h_brand'

    resources :shf_documents, path: 'dokument'

    get 'dokument/innehall/:page',
      to: 'shf_documents#contents_show', as: 'contents_show'

    get 'dokument/innehall/:page/redigera',
      to: 'shf_documents#contents_edit', as: 'contents_edit'

    patch 'dokument/innehall/:page',
      to: 'shf_documents#contents_update', as: 'contents_update'

    get 'medlemssidor', to: 'shf_documents#minutes_and_static_pages',
                        as: 'member_pages'
  end

  # We are not using nested resource statements for the following routes
  # because that did not seem to work when used in combination with "path:" option

  # ------- Payment as a nested resource within user --------
  post 'anvandare/:user_id/betalning/:type', to: 'payments#create',
       as: :payments

  get 'anvandare/:user_id/betalning/:id', to: 'payments#confirmation',
      as: :payment_confirmation

  post 'anvandare/betalning/klarna_push', to: 'payments#klarna_push',
       as: :payment_klarna_push
  # ----------------------------------------------------------

  # ------- Address as a nested resource within company -----
  post 'hundforetag/:company_id/adresser/:id/set_type', to: 'addresses#set_address_type',
       as: :company_address_type  # Used only for XHR action, not visible to user

  get 'hundforetag/:company_id/ny', to: 'addresses#new', as: :new_company_address

  post 'hundforetag/:company_id/adresser', to: 'addresses#create',
       as: :company_addresses

  get 'hundforetag/:company_id/adresser/:id/redigera', to: 'addresses#edit',
       as: :edit_company_address

  put 'hundforetag/:company_id/adresser/:id', to: 'addresses#update',
       as: :company_address

  delete 'hundforetag/:company_id/adresser/:id', to: 'addresses#destroy',
         as: :company_address_delete
  # ----------------------------------------------------------

app/helpers/user_checklists_helper.rb
require_relative File.join(__dir__, 'data_post_checkbox_helper')

module UserChecklistsHelper

  include DataPostCheckboxHelper

  # TODO: use fa_checkbox method in ApplicationHelper
  # @return HTML safe string for a FontAwesome checkbox. Is checked if the user_checklist is complete
  #
  def fa_is_complete_checkbox(user_checklist, options = {})

    checkbox_icon = 'square' # default
    title = I18n.t('activerecord.attributes.user_checklist.not_completed')

    if user_checklist.all_completed?
      checkbox_icon = 'check-square'
      title = I18n.t('activerecord.attributes.user_checklist.completed')
    end
    html_options = { title: "#{user_checklist.name} #{title}" }.merge(options)

    icon('far', checkbox_icon, html_options)
  end


  # Checkbox for whether or not a UserChecklist is completed.
  #  TODO: is this used?
  #
  # @param [UserChecklist] user_checklist - the user checklist that may or may not be completed
  #
  # @return [String] - html_safe string that is a checkbox with a label for it
  def is_completed_checkbox(user_checklist, options = {})
    checkbox_with_post('completed-checkbox',
                       'checked',
                       user_checklist.all_completed?,
                       user_checklist_all_changed_by_completion_toggle_path(user_checklist), options)
  end


  # @return [Lambda] - lambda to use to generate the ul element id based on the user_checklist
  def ul_id(prefix = 'ul-id-')
    lambda { |user_checklist| "#{prefix}#{user_checklist.id}" }
  end


  # @return [Lambda] - lambda to use to generate the li element id based on the user_checklist
  def li_id(prefix = 'li-id-')
    lambda { |user_checklist| "#{prefix}#{user_checklist.id}" }
  end


end

app/views/user_checklists/_checklist_header.html.haml
-# This partial expects these locals:
  current_user [User] - the current user; used to determine what CSS classes to apply
  user_checklist [UserChecklist] - the checklist that will be displayed in the header

%header.entry-header
  = content_title(user_checklist.name, user: current_user)

app/views/user_checklists/_checklist_top_desc.html.haml
-# Display the description of the root of the user_checklist
    This partial expects these locals (required):
      user_checklist [UserChecklist] - the UserChecklist that is used

-#%p.description= local_assigns[:user_checklist].root.description
-# Do not display this for now.  Will display this later. (Uncomment out the statement above and remove these comments)
    See PT story https://www.pivotaltracker.com/story/show/172961791

app/views/user_checklists/_checklist_tree_as_list.html.haml
-# This partial expects these locals:
  user_checklist [UserChecklist] - the checklist that will be displayed a list

- if user_checklist.children?
  = arranged_tree_as_list(user_checklist.children.arrange,
         { sort_by: [:list_position],
         list_type: 'ul',
          ul_class: ['checklist-items' ],
          ul_id_method: ul_id,
          li_class: ['checklist-item'],
          }) do | child_entry |
    %span.name{ class: list_entry_css_classes(child_entry) }
      = child_entry.name.html_safe

app/views/user_checklists/_membership_term_card.html.haml
-#  Bootstrap 4 Card for a Membership Guideline that has sub-guidelines (UserChecklist)
  This partial expects these locals:

  user_checklist [UserChecklist] - a checklist
  user - the user this UserChecklist is for
  overall_percent_complete - the initial percent complete for the progress bar.

.card
  .card-body

    %h4.card-title
      %span.is-complete-icon.show-inline.fa-fw#is-complete-icon= complete_check_icon
      = user_checklist.name

    - if user_checklist.children?
      = arranged_tree_as_list(user_checklist.children.arrange,
             { sort_by: [:list_position],
             list_type: 'ul',
              ul_class: ['checklist-items' ],
              ul_id_method: ul_id,
              li_class: ['checklist-item'],
              li_id_method: li_id }) do | child_entry |

        - child_entry_li_id = li_id.call(child_entry)
        %span.name{ class: list_entry_css_classes(child_entry) }
          = child_entry.name


      %p.have-read-confirmation
        = check_box_tag("completed-checkbox", 'checked', user_checklist.all_completed?,
          { class: "checkbox-date-completed",
            onchange:"toggleCompletedCheckbox(#{ user.id }, #{ user_checklist.id })" })
        I have read and agree to all of the
        %span.name= user_checklist.name
        terms.

  .card-footer
    .row
      - prev_sibling = user_checklist.previous_sibling
      - if prev_sibling
        .col.text-left= link_to 'Prev.',  user_user_checklist_progress_path(user, prev_sibling)
      - next_sibling = user_checklist.next_sibling
      - if next_sibling
        .col.text-right= link_to 'Next.', user_user_checklist_progress_path(user, next_sibling)


:javascript

  const setCompleteUrl = "/anvandare/lista/set-all-completed/";
  const setUncompleteUrl = "/anvandare/lista/set-all-uncompleted/";

  const checkboxId = "completed-checkbox";
  const isCompleteIconId = "is-complete-icon";


  window.onload = function(){
    updateBasedOnCompletedCheckbox();
  };


  function toggleCompletedCheckbox(userId, checklistId) {
      let checkbox = getCheckboxElement();
      let ajaxPostURL = (checkbox.checked ? setCompleteUrl : setUncompleteUrl);
      $.post( ajaxPostURL + checklistId, updateDateSuccessfulFor); // FIXME catch error and display as an alert
  }


  function updateDateSuccessfulFor(responseData) {

    updateBasedOnCompletedCheckbox();

    // FIXME update overall percent complete
    let changedChecklistId = responseData.user_checklist_id;
    let newPercentComplete = responseData.overall_percent_complete;
    console.log('id = ' + changedChecklistId + '  new percent complete: ' + newPercentComplete);
  }


  function updateBasedOnCompletedCheckbox() {
   let checkbox = getCheckboxElement();
    if (checkbox.checked) {
      showCompleteCheckIcon();
    }
    else {
      hideCompleteCheckIcon();
    }
  }


  function hideCompleteCheckIcon() {
    let checkCompleteIcon = getCheckedCompleteIconElement();
    checkCompleteIcon.classList.remove('show-inline');
    checkCompleteIcon.classList.add('hide');
  }


  function showCompleteCheckIcon() {
    let checkCompleteIcon = getCheckedCompleteIconElement();
    checkCompleteIcon.classList.remove('hide');
    checkCompleteIcon.classList.add('show-inline');
  }


  function getCheckboxElement() {
    return document.getElementById(checkboxId);
  }

  function getCheckedCompleteIconElement() {
    return document.getElementById(isCompleteIconId);
  }

app/views/user_checklists/membership_guidelines_completed.html.haml
.membership-guidelines
  - overall_progress = @overall_progress

  = render partial: 'checklist_header', locals: { user: @current_user, user_checklist: @user_checklist.root }

  .entry-content.container
    .user-checklist.membership-guidelines-completed
      = render partial: 'user_checklists/checklist_top_desc', locals: {user_checklist: @user_checklist}

      .completed-progress-bar
        = render partial: 'shared/progress_bar', locals: {  percent_complete: overall_progress }

      .row
        .col
          -# Can't make the card a shared partial because the other view that uses this card needs to update the progress bar.
          -# This is an excellent use case for using Vue or React (to take advantage of components automatically reacting to change)
          .card
            .card-body
              %h3.card-title= t('.i_commit_to')

              = render partial: 'checklist_tree_as_list', locals: { user_checklist: @user_checklist.root }

            .card-footer
              .row.justify-content-center
                %h4
                  %span.is-complete.show-inline#all-complete-icon
                    = complete_check_icon(html_options: { class: 'fa-fw', id: 'fas-all-complete-icon' })
                  = t('.agreed_to_all_terms')
              .row.justify-content-center
                %p= link_to t('.back_to_my_profile'), user_path(@user), class: 'btn btn-sm btn-primary'

app/views/user_checklists/show.html.haml
- content_for :javascript_for_view do
  = javascript_include_tag 'user-checklists.js'

-# The variables below are also used in the javascript.  They're here so
  that the javascript looks for the same element names as are used to construct the view.
:ruby
  checkbox_date_completed_cls = "checkbox-date-completed"
  date_completed_id = "date-completed"
  date_completed_value_id = "date-completed-value"
  i18n_date_completed = t('checklist_common.date_completed')
  li_id = "li-id-#{ @user_checklist.id }"
  checkbox_id = "completed-checkbox-#{ li_id }"
  complete_text = t('.complete')

= render partial: 'checklist_header', locals: { user: @current_user, user_checklist: @user_checklist }

.entry-content.container

  #user-checklist
    .row.mt-2
      .col
        - unless @user_checklist.description.nil?
          %p
            %b #{ t('.description') }:
            = @user_checklist.description

    - if @current_user.admin?
      .row.mt-2
        .col
          %p
            %b
              -# TODO i18n
              For user #{ @user_checklist.user.full_name }


    = render partial: 'shared/progress_bar', locals: { percent_complete: @user_checklist.percent_complete }

    .row.mt-2
      .col-sm-3
        %p{ style: "display: #{ @user_checklist.children? ? 'none' : 'inherit' }" }
          %b
            = t('.completed') + '?'
            - disabled_setting = @user_checklist.children? ? { disabled: true } : { }
            = check_box_tag(checkbox_id, 'checked', @user_checklist.all_completed?, { class: checkbox_date_completed_cls,
                onchange:"toggleCompletedCheckbox( #{ @user_checklist.id })" }.merge(disabled_setting))

      .col
        %p.date-completed{ id: date_completed_id, style: 'display: none' }
          = i18n_date_completed + ':'
          %span{ id: date_completed_value_id }
            = @user_checklist.date_completed if @user_checklist.date_completed


    .ordered-list-entry
      - if @user_checklist.ancestors?
        .row.mt-2
          .col
            %p
              -# TODO I18n
              %b In user checklist
              = link_to @user_checklist.parent.name, user_user_checklist_path(@user_checklist.parent.user, @user_checklist.parent), class: list_entry_css_classes(@user_checklist.parent.master_checklist)


      - if @user_checklist.children?
        -# TODO: I18n 'Items'
        %h4.children Items:
        = arranged_tree_as_list(@user_checklist.children.arrange,
         { sort_by: [:list_position], list_type: :ol,
          ul_class: ['child-entries'], li_class: ['child-entry'] }) do | child_entry |
          -# = fa_is_complete_checkbox(child_entry)
          = link_to  child_entry.name,
                    user_user_checklist_path(child_entry.user, child_entry),
                    class: list_entry_css_classes(child_entry)
          - if child_entry.all_completed?
            %span.date-completed
              = i18n_date_completed + ': ' + child_entry.date_completed.to_s
          - else
            = "#{ child_entry.percent_complete }% complete"


  - if @current_user.admin?
    %hr
      .text-center
        - all_lists_str = @current_user.admin? ?  t('.all_list_items_for_user', name: @user_checklist.user.full_name) : t('.all_list_items')
        = link_to all_lists_str, user_checklists_path, class: 'btn btn-sm btn-light'


:javascript
  "use strict";

  const dateCompletedId = "##{date_completed_id}"
  const checkboxId = "##{checkbox_id}";
  const completeText = "#{complete_text}";
  const dateCompletedI18n = "#{i18n_date_completed}";


  window.onload = function(){
    // update the Progress bar
    let percentComplete = parseInt("#{@user_checklist.percent_complete}");
    let progressBar = $(UserChecklists.PROGRESS_BAR_ID);
    UserChecklists.updateProgressBar(percentComplete, progressBar, completeText)

    displayOrHideDateCompleted();
  };

  // show the date completed if completed checkbox is checked; hide otherwise
  function displayOrHideDateCompleted(dateCompleted = "#{@user_checklist.date_completed}") {
    let checkBox = $(checkboxId);
    let dateCompletedElem = $(dateCompletedId);
    let dateCompletedStr = UserChecklists.dateCompletedText(dateCompleted, dateCompletedI18n)
    dateCompletedElem.text(dateCompletedStr);
    dateCompletedElem[0].style.display = (checkBox[0].checked ? "block" : "none");
  }


  function toggleCompletedCheckbox(checklistId) {
    let ajaxPostURL = UserChecklists.toggleAllUrl( checklistId );
    Utility.postUrl(ajaxPostURL, toggleAllSuccess);
  }


  // This is called if postUrl is successful
  function toggleAllSuccess(responseData) {
    let progressBar = $(UserChecklists.PROGRESS_BAR_CLASS);
    UserChecklists.updateProgressBarFromResponse(responseData, progressBar, completeText);
    let dateCompletedStr = responseData.date_completed === null ? '' : responseData.date_completed.toString();
    displayOrHideDateCompleted(dateCompletedStr);
  }

app/views/user_checklists/show_progress.html.haml
- content_for :javascript_for_view do
  = javascript_include_tag 'user-checklists.js'

-# The variables below are also used in the javascript
:ruby
  checkbox_id = 'completed-checkbox'
  complete_txt = t('.complete')

  is_completed_icon_id = 'fas-is-complete-icon'
  next_link_id = 'next-link'
  contact_us_footer_id = 'contact-us-footer'

  whiteout_class = 'whiteout'
  show_class = 'is-complete'


.membership-guidelines
  - overall_progress = @overall_progress

  = render partial: 'checklist_header', locals: { user: @current_user, user_checklist: @checklist_root }

  .entry-content.container
    .user-checklist
      = render partial: 'user_checklists/checklist_top_desc', locals: {user_checklist: @user_checklist}

      = render partial: 'shared/progress_bar', locals: {  percent_complete: overall_progress }

      %p.instructions= t('.read_and_agree')

      .row
        .col
          -# Can't make the card a partial because we need to update the progress bar.
          -# This is an excellent use case for using Vue or React (to take advantage of components automatically reacting to change)
          .card
            .card-body

              %h4.card-title#guideline-name
                %span.is-complete.show-inline#is-complete-icon

                  -# The 'fa-fw' class is essential: That font awesome class sets a fixed width no matter what icon is shown.
                  -# It keeps the content to the right of the icon from 'jumping over' when there is no icon to display.
                  = complete_check_icon(html_options: { class: "fa-fw #{ whiteout_class }", id: is_completed_icon_id })

                = @user_checklist.name

              .agree-to-sub-guidelines
                %p.i-commit-to= t('.i_commit_to')

                = render partial: 'checklist_tree_as_list', locals: { user_checklist: @user_checklist }

                %p.have-read-confirmation

                = check_box_tag(checkbox_id, 'checked', @user_checklist.all_completed?,
                    { class: "fa-check-square",
                      onchange:"toggleCompletedCheckbox( #{ @user_checklist.id })" })

                = label_tag checkbox_id, { onchange:"toggleCompletedCheckbox( #{ @user_checklist.id })" } do
                  = t('.read_and_agree_start')
                  %span.name= @user_checklist.name
                  = t('.read_and_agree_end')

            .card-footer
              .row
                .col
                  %p.contact-if-questions
                    %div{ id: contact_us_footer_id }
                      = t('.contact_if_questions')
                      = mail_to(t('.email_display_name'), ENV['SHF_MEMBERSHIP_EMAIL'])

                  - next_sibling = @user_checklist.next_sibling
                  - if next_sibling
                    -# Start with this not displayed; javascript below will display it via onchange
                    -# Could use a class to change the display to none vs. setting it explicitly here. (Be careful to ensure that the DOM is set/updated correctly, especially for tests.)
                    .next{ id: next_link_id, style: 'display: none;' }
                      = link_to  user_user_checklist_progress_path(@user, next_sibling) do
                        = t('.next')
                        %span.next-arrow-icon.show-inline#next-arrow-icon
                          = next_arrow_icon(html_options: { class: 'fa-lg', id: 'fas-next-arrow-icon' })


:javascript
  "use strict";

  const checkboxId = "##{ checkbox_id }";
  const isCompleteIconId = "##{ is_completed_icon_id }";

  const nextLinkId = "##{ next_link_id }";
  const contactUsFooterId = "##{ contact_us_footer_id }";

  const whiteoutClass = "#{ whiteout_class }";
  const showClass = "#{ show_class }";

  const completeTxt = "#{ complete_txt }"


  window.onload = function(){
    updateBasedOnCompletedCheckbox();
  };


  function toggleCompletedCheckbox(checklistId) {
      UserChecklists.postCheckboxChanged(checkboxId, checklistId, postCheckboxChangedSuccess);
  }


  // This is called if postCheckboxChanged is successful
  function postCheckboxChangedSuccess(responseData) {

    if (Utility.httpErrorOccurred(responseData) === false) {
        // success
        updateBasedOnCompletedCheckbox();
        let newPercentComplete = responseData.overall_percent_complete;
        let progressBar = $(UserChecklists.PROGRESS_BAR_ID);
        UserChecklists.updateProgressBar(newPercentComplete, progressBar, completeTxt);
        if (newPercentComplete === UserChecklists.ALL_COMPLETE) {
          window.location.reload(true);
        }
    }
  }


  function updateBasedOnCompletedCheckbox() {
    let checkbox = $(checkboxId);
    if (checkbox.prop("checked")) {
      showCompleteCheckIcon();
      hideContactUs();
      showNextLink();
    }
    else {
      hideCompleteCheckIcon();
      showContactUs();
      hideNextLink();
    }
  }


  function showContactUs() {
    $(contactUsFooterId).toggle(true);
  }

  function hideContactUs() {
    $(contactUsFooterId).toggle(false);
  }

  function showNextLink() {
    $(nextLinkId).toggle(true);
  }

  function hideNextLink() {
    $(nextLinkId).toggle(false);
  }

  function hideCompleteCheckIcon() {
    $(isCompleteIconId).toggleClass(showClass, false).toggleClass(whiteoutClass, true);
  }

  function showCompleteCheckIcon() {
    $(isCompleteIconId).toggleClass(showClass, true).toggleClass(whiteoutClass, false);
  }