config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  filter :locale

  # Override Devise::RegistrationsController so that we can do some custom things.
  devise_for :users, controllers: { registrations: 'registrations' }

  as :user do

    authenticated :user, lambda { |u| u.admin? } do

      namespace :admin_only, path: 'admin' do
        resources :master_checklists
        get  'master-checklists/max-list-position', to: 'master_checklists#max_list_position'
        post 'master-checklists/toggle-in-use', to: 'master_checklists#toggle_in_use'
        post 'master-checklists/set-to-no-longer-used/:id', to: 'master_checklists#set_to_no_longer_used',
             as: :master_checklists_set_to_no_longer_used

        get 'master-checklists/next-onebased-list-position', to: 'master_checklists#next_one_based_list_position'

        get 'payments', to: 'dashboard#payments'

        resources :master_checklist_types

        # Update membership status for all users
        get 'anvandare/update-membership-status-all', to: 'user_account#update_membership_status_all',
            as: :update_membership_status_all

      end


      # UserChecklists - that only an admin do:
      # View all the checklists for a user
      get 'admin/anvandare/:user_id/lista', to: 'user_checklists#index',
          as: 'user_checklists'

      # Export Information (CSV files)
      post 'admin/export-ansokan-csv'
      post 'admin/export-payments-csv'
      put 'admin/export-payments-covering-year-csv'

      # Route for testing Exception Notification configuration
      get "test_exception_notifications" => "application#test_exception_notifications"

      root to: 'shf_applications#index', as: :admin_root

    end
  end

  # ---------------------------------------------------------------------------
  # We're already using 'admin' as the name of a user role, so we
  # use "admin_only" here to avoid colliding with that term with the
  # namespace directories and class names.  We keep 'admin' as the path
  # for simplicity and some consistency.
  # namespace :admin_only, path: 'admin' do
  namespace :admin_only, path: 'admin' do

    resources :member_app_waiting_reasons

    get 'dashboard', to: 'dashboard#index'
    put 'dashboard_timeframe', to: 'dashboard#update_timeframe'

    put 'dashboard_show_recent_activity', to: 'dashboard#show_recent_activity'


    # AppConfiguration is a Singleton.
    # Admins only view and edit the AppConfiguration.
    # There is no need for index or destroy.
    #
    # :id is an optional parameter so that view buttons, etc., work fine
    # with the Rails conventions
    #
    # as: :..app_configuration..  is needed when the id is an optional parameter

    get 'app_configuration(/:id)/redigera', to: 'app_configuration#edit',
        as: :edit_app_configuration

    # must use the as: :put_app_configuration so that the method does not conflict with get 'app_configuration(/:id)' route (#show)
    put 'app_configuration(/:id)', to: 'app_configuration#update', as: :put_app_configuration

    get 'app_configuration(/:id)', to: 'app_configuration#show', as: :app_configuration


    get 'user_profile_edit/:id', to: 'user_profile#edit', as: :user_profile_edit
    put 'user_profile_update/:id', to: 'user_profile#update', as: :user_profile_update
    get 'user_profile_become/:id', to: 'user_profile#become', as: :become_user

    # Edit User Account
    get 'anvandare/:user_id/redigera', to: 'user_account#edit', as: :edit_user_account
    put 'anvandare/:user_id', to: 'user_account#update', as: :user_account

    # Design Guide
    get 'designguide', to: 'design_guide#show'

  end
  # ---------------------------------------------------------------------------

  get '/pages/*id', to: 'pages#show', as: :page, format: false


  scope(path_names: { new: 'ny', edit: 'redigera' }) do
    resources :business_categories, path: 'kategori' do
      get :get_edit_row, on: :member
      get :get_display_row, on: :member
    end

    resources :shf_applications, path: 'ansokan' do
      member do
        put 'remove_attachment'

        put 'update-reason-waiting', to: 'shf_applications#update_reason_waiting',
            as: 'reason_waiting'

        get 'start-review', to: 'shf_applications#show'
        post 'start-review', to: 'shf_applications#start_review'

        get 'accept', to: 'shf_applications#show'
        post 'accept', to: 'shf_applications#accept'
        get 'reject', to: 'shf_applications#show'
        post 'reject', to: 'shf_applications#reject'
        get 'need-info', to: 'shf_applications#show'
        post 'need-info', to: 'shf_applications#need_info'
        get 'cancel-need-info', to: 'shf_applications#show'
        post 'cancel-need-info', to: 'shf_applications#cancel_need_info'
        get 'need-payment', to: 'shf_applications#show'
        post 'need-payment', to: 'shf_applications#need_payment'
        get 'cancel-need-payment', to: 'shf_applications#show'
        post 'cancel-need-payment', to: 'shf_applications#cancel_need_payment'
        get 'received-payment', to: 'shf_applications#show'
        post 'received-payment', to: 'shf_applications#received_payment'

        get 'get_edit_row_business_category'
        get 'get_display_row_business_category'

        put 'business_subcategories'
      end

    end

    resources :companies, path: 'hundforetag' do
      member do
        put 'edit_payment', to: 'companies#edit_payment', as: 'edit_payment'
        post 'fetch_from_dinkurs', to: 'companies#fetch_from_dinkurs', as: 'fetch_from_dinkurs'
      end
    end


    # User Account.  Only admins can edit (see the route above for /admin)
    # Note that this sets the default id parameter to :user_id (instead of just :id)
    resources :users, path: 'anvandare', except: [:edit, :update]  do

      # this will add an :id parameter
      member do
        put 'edit_status', to: 'users#edit_status', as: 'edit_status'

        # User Payment Receipts
        get 'betalning-kvitton', to: 'users#view_payment_receipts',
            as: 'view_payment_receipts'
        get 'betalning-kvitton-ladda-ner', to: 'users#download_payment_receipts_pdf',
            as: 'download_payment_receipts_pdf'
      end

      post 'toggle_membership_package_sent', to: 'users#toggle_membership_package_sent'

      # ---------------------------------------------------
      # UserChecklist as a nested resource under User, with path '/lista' in the URI
      resources :user_checklists, only: [:show], path: 'lista' do
        get 'progress', to: 'user_checklists#show_progress'
      end


      # ---------------------------------------------------
      # Uploaded files

      # Do these 2 routes manually so that we can add the optional parameter :from_acct_pg
      # They must go before the resources :uploaded_files... statement below so that
      #  /anvandare/:user_id/filer/ny is matched to the request before
      #  /anvandare/:user_id/filer/:id  otherwise the router will think that :id = 'ny'
      #
      get 'filer/ny(/:from_acct_pg)', to: 'uploaded_files#new',
          as: 'new_uploaded_file'
      post 'filer/(/:from_acct_pg)', to: 'uploaded_files#create'

      # UploadedFile as a nested resource under User, with page '/filer' in the URI
      resources :uploaded_files, path: 'filer', except: [:new, :create]

    end

    # UserChecklists
    post 'anvandare/lista/all_changed_by_completion_toggle/:id', to: 'user_checklists#all_changed_by_completion_toggle',
         as: 'user_checklist_all_changed_by_completion_toggle'
    post 'anvandare/lista/set-all-completed/:id', to: 'user_checklists#set_complete_including_kids',
         as: 'user_checklist_set_complete_including_kids'
    post 'anvandare/lista/set-all-uncompleted/:id', to: 'user_checklists#set_uncomplete_including_kids',
         as: 'user_checklist_set_uncomplete_including_kids'


    get 'anvandare/:id/proof_of_membership', to: 'users#proof_of_membership',
        as: 'proof_of_membership'

    get 'hundforetag/:id/company_h_brand', to: 'companies#company_h_brand',
        as: 'company_h_brand'

    resources :shf_documents, path: 'dokument'

    get 'dokument/innehall/:page',
      to: 'shf_documents#contents_show', as: 'contents_show'

    get 'dokument/innehall/:page/redigera',
      to: 'shf_documents#contents_edit', as: 'contents_edit'

    patch 'dokument/innehall/:page',
      to: 'shf_documents#contents_update', as: 'contents_update'

    get 'medlemssidor', to: 'shf_documents#minutes_and_static_pages',
                        as: 'member_pages'
  end

  # We are not using nested resource statements for the following routes
  # because that did not seem to work when used in combination with "path:" option

  # ------- Payment as a nested resource within user --------
  post 'anvandare/:user_id/betalning/:type', to: 'payments#create',
       as: :payments

  get 'anvandare/:user_id/betalning/:id', to: 'payments#confirmation',
      as: :payment_confirmation

  post 'anvandare/betalning/klarna_push', to: 'payments#klarna_push',
       as: :payment_klarna_push
  # ----------------------------------------------------------

  # ------- Address as a nested resource within company -----
  post 'hundforetag/:company_id/adresser/:id/set_type', to: 'addresses#set_address_type',
       as: :company_address_type  # Used only for XHR action, not visible to user

  get 'hundforetag/:company_id/ny', to: 'addresses#new', as: :new_company_address

  post 'hundforetag/:company_id/adresser', to: 'addresses#create',
       as: :company_addresses

  get 'hundforetag/:company_id/adresser/:id/redigera', to: 'addresses#edit',
       as: :edit_company_address

  put 'hundforetag/:company_id/adresser/:id', to: 'addresses#update',
       as: :company_address

  delete 'hundforetag/:company_id/adresser/:id', to: 'addresses#destroy',
         as: :company_address_delete
  # ----------------------------------------------------------

app/helpers/companies_helper.rb
module CompaniesHelper

  # FIXME this should be the responsibility of the CompanyPolicy
  def payment_visible_for_user?(user, company)
    user.admin? || user.in_company_numbered?(company.company_number)
  end


  def list_categories(company, separator=' ', include_subcategories=false)
    company.current_category_names(include_subcategories).join(separator)
  end


  # return a nicely formed URI for the company website
  # if the company website starts with with https://, return that.
  #  else ensure it starts with 'http://'
  def full_uri company
    uri = company.website
    uri =~ %r(https?://) ? uri : "http://#{uri}"
  end


  # Given a collection of companies, create an array of {latitude, longitude, marker}
  # for each company.  (Can be used by javascript to display markers for many companies)
  # if link_name is true (the default), the name of each company should be a link to its page
  #  else the name of each company should just be the name with no link to it
  def location_and_markers_for(companies, link_name: true)
    companies.flat_map do |company|
      name_html = link_name ?  nil : company.name

      company.addresses_visible.map do |address|
        { latitude: address.latitude,
          longitude: address.longitude,
          text: html_marker_text(company, address, name_html: name_html) }
      end
    end
  end


  # html to display for a company when showing a marker on a map
  #  if no name_html is given (== nil), it will be linked to the company,
  #  else the name_html string will be used
  def html_marker_text(company, address, name_html: nil)
    text = "<div class='map-marker'>"
    text << "<p class='name'>"
    text << (name_html.nil? ? link_to(company.name, company, target: '_blank') : name_html)
    text << "</p>"
    text << "<p class='categories'>#{list_categories(company, ', ')}</p>"
    text << "<p class='entire-address'>#{address.entire_address}</p>"
    text << "</div>"

    text
  end

  # Creates an array which contains an array of [text, value]
  #  for each company address_visibility level (for selection in form)
  def address_visibility_array
    Address.address_visibility_levels.map do |visibility_level|
      [ I18n.t("address_visibility.#{visibility_level}"), visibility_level ]
    end
  end


  def html_postal_format_entire_address(co, person_name: nil)
    lines = postal_format_entire_address(co, person_name: person_name)
    tag.div class: 'postal-address' do
      lines.map{|line| concat tag.p line}.join(' ')
    end
  end


  # Return the entire address in the postal mailing format for Sweden
  # Ignore address visibility settings (TODO: is this what we want? should this method be authorized)
  def postal_format_entire_address(co, person_name: nil)
    first_lines = person_name.nil? ? [co.name] : [co.name, person_name.to_s]

    address_lines = []
    # address_items = co.main_address.address_array(Address.max_visibility)
    address = co.main_address
    address_lines << address.street_address
    address_lines << "#{address.post_code} #{address.city}"

    first_lines + address_lines
  end


  def company_number_selection_field(company_id=nil)
    select_tag :company_id,
       options_from_collection_for_select(Company.order(:company_number),
                  :id, :company_number, company_id),
       class: 'search_field',
       data: {language: "#{@locale}" }
  end


  def company_display_name(company)
    company.name.blank? ? t('name_missing') : company.name
  end


  def company_number_entry_field(company_numbers)
    text_field_tag :company_number, company_numbers,
                     id: 'shf_application_company_number',
                     class: 'form-control'
  end

  def company_h_brand_jpg_url(company)
    company_h_brand_url(company, format: :jpg)
  end

  def short_h_brand_url(company)
    url = company_h_brand_jpg_url(company)
    company.get_short_h_brand_url(url)
  end
end

app/views/companies/_branding_term_status.html.haml
-# FIXME how is the company id used in payments_path below? is it a parameter or argument?
  It does not appear in the list of routes (rake routes)) but is used as an argument by the PaymentsController
- payment_action_path = payments_path(user_id: current_user.id,
  company_id: company.id,
  type: company.class::THIS_PAYMENT_TYPE)

#company-branding-status
  = render partial: 'payor/term_status',
   locals: { entity: company,
  status_text: company.branding_license? ? t('companies.show.hbrand_status_paid') : t('companies.show.hbrand_status_not_paid'),
  fee_name_payment: t('companies.show.hbrand_term_payment'),
  term_name: t('companies.show.hbrand_term'),
  term_end: company.branding_expire_date,
  next_term_end: Company.next_membership_payment_dates(company.id).last,
  can_make_payment: current_user.allowed_to_pay_hbrand_fee?(company),
  payment_text: t('menus.nav.company.pay_branding_fee'),
  payment_action_path: payment_action_path,
  admin_edit_status_text: t('companies.show.edit_branding_status'),
  admin_edit_target_id: '#edit-branding-modal' }

app/views/companies/_companies_list.html.haml
#companies-list-table
  .table-responsive-lg
    %table.table.table-hover.table-md
      %thead
        %tr
          -# The .companies_pagination style is what triggers the Javascript to replace the #companies_list page content
              @see app/assets/javascripts/companies.js
          %th
            = t('activerecord.models.business_category.one')
          %th
            = sort_link(search_params, :name,
                        t('activerecord.attributes.company.name'), {},
                        { class: 'companies_pagination', remote: true })
          %th
            = sort_link(search_params, :addresses_region_name,
                        t('activerecord.attributes.address.region'), {},
                        { class: 'companies_pagination', remote: true })
          %th
            = sort_link(search_params, :addresses_kommun_name,
                        t('activerecord.attributes.address.kommun'), {},
                        { class: 'companies_pagination', remote: true })
          %th
            = t('activerecord.attributes.address.city')

          - if current_user.admin?
            %th
              = sort_link(search_params, :company_number,
                        t('activerecord.attributes.company.company_number'), {},
                        { class: 'companies_pagination', remote: true })
            %th
              = sort_link(search_params, :information_complete,
                      "#{t('companies.index.complete')}?", {},
                      { class: 'complete-status companies_pagination', remote: true })
            %th
              = sort_link(search_params, :id,
                        'db id', {},
                        { class: 'db-id companies_pagination', remote: true })
            %th
            %th

      %tbody
        - companies.each do |company|
          %tr.company{class: company.information_complete? ? '' : 'not-complete' }
            %td.categories
              = safe_join(company.current_category_names(false), tag.br)
            %td.name= link_to company_display_name(company), company
            %td.region
              = safe_join(company.addresses_region_names, tag.br)
            %td.kommun
              = safe_join(company.kommuns_names, tag.br)
            %td.city
              = safe_join(company.cities_names, tag.br)

            - if current_user.admin?
              %td.company-number= company.company_number
              %td.complete= (company.information_complete? ? t('yes') : t('no'))
              %td.db-id= company.id
              %td.edit= link_to icon('fas', 'edit'), edit_company_path(company)
              %td.delete= link_to icon('fas', 'trash', class: 'delete'), company, method: :delete,
                              data: { :confirm => "#{t('confirm_are_you_sure')}" }


= render 'application/paginate_footer', entities: companies,
                                        paginate_class: 'companies_pagination',
                                        items_count: @items_count,
                                        url: companies_path

app/views/companies/_company_addresses.html.haml
- addresses = user_can_edit ? company.addresses : company.addresses.visible

- if addresses.any?
  .row
    .col-12
      .table-responsive-lg
        %table.table.table-sm.table-hover
          %thead
            %tr
              %th
                = t('companies.show.address')
                = " (#{t('companies.show.click_to_edit')})" if user_can_edit

              - if user_can_edit

                %th= t('companies.address_visibility')
                %th= t('companies.show.mailing_address')

          - addresses.includes(:kommun).order(:street_address).each do |address|
            %tbody
              %tr.address
                - if user_can_edit
                  - radio_btn_id =  "cb_address_#{address.id}"
                  %td
                    = label_tag(radio_btn_id) do
                      = link_to address.entire_address(full_visibility: true),
                              edit_company_address_path(company.id, address.id)
                  %td
                    %span{ class: (address.visibility == 'none' ? 'maybe' : 'yes') }
                      = t("address_visibility.#{address.visibility}")
                  %td
                    = radio_button_tag('mail', '1', address.mail,
                        class: 'cb_address',
                        id: radio_btn_id,
                        data: { remote: true,
                                url: company_address_type_path(company.id, address.id),
                                params: 'type=mail',
                                method: :post })
                - else
                  %td
                    = address.entire_address

app/views/companies/_company_create_modal.html.haml
.modal.fade#company-create-modal{ tabindex: '-1', role: 'dialog' }
  .modal-dialog{ role: 'document' }
    .modal-content
      = form_for company, url: companies_path,
                 method: :post, remote: true,
                 html: { id: 'companyCreateForm' } do |f|

        .modal-header
          %h4.modal-title.text-center
            = t('companies.new.title')
          %button.close{ type: 'button', data: { dismiss: 'modal' } }
            %span{ 'aria-hidden' => 'true' } &times;

        .modal-body
          .container-fluid

            #company-create-errors
              != model_errors_helper(company)

            .form-group
              .row
                .col

                  = f.label :company_number, "#{t('.company_number')}:",
                            class: 'required', for: 'company-number-in-modal'
                  = fas_tooltip(t('companies.form.org_nr_tooltip'))

                .col
                  = f.number_field :company_number, class: 'form-control', size: 10,
                                   id: 'company-number-in-modal'
              %hr
              .row
                .col

                  = f.label :email, "#{t('companies.show.email')}:", class: 'required'

                .col

                  = f.email_field :email, class: 'form-control', size: 30

        .modal-footer
          = f.submit t('companies.create.create_submit'), class: "btn btn-primary form-control",
                     id: 'companyCreateSubmit'

          %button{ type: 'button', class: 'btn btn-outline-secondary', data: { dismiss: 'modal' } }
            = t('cancel')

app/views/companies/_custom_context_menu.html.haml
%ul.custom-menu
  %li{ "data-action" => "download" }= t('users.show.download_image')
  %li{ "data-action" => "link" }= t('users.show.copy_image_url')
  %li{ "data-action" => "show" }= t('users.show.show_image')

app/views/companies/_edit_branding_modal.html.haml
.modal.fade#edit-branding-modal{ tabindex: '-1', role: 'dialog' }
  .modal-dialog{ role: 'document' }
    .modal-content

      = form_for company, url: edit_payment_company_path(company),
                 method: :put, remote: true,
                 html: { id: 'brandingStatusForm' } do |f|

        .modal-header
          %h4.modal-title.text-center
            = t('companies.show.edit_branding_status')
          %button.close{ type: 'button', data: { dismiss: 'modal' } }
            %span{ 'aria-hidden' => 'true' } &times;

        .modal-body
          .container-fluid
            = fields_for :payment, company.most_recent_branding_payment do |pf|
              %label #{t('activerecord.attributes.payment.expire_date')}:
              = pf.date_select(:expire_date,
                               { start_year: Time.current.year,
                                 end_year: Time.current.year + 2},
                               { class: 'form-control select-box form-control-sm' })
              %hr
              = pf.label :notes,
                         "#{t('activerecord.attributes.payment.notes')}:"
              = pf.text_area :notes, class: 'form-control'

        .modal-footer
          = f.submit t('companies.company.submit_button_label'), class: "btn btn-primary form-control",
                     id: 'editBrandingStatusSubmit'

          %button{ type: 'button', class: 'btn btn-outline-secondary', data: { dismiss: 'modal' } }
            = t('cancel')

app/views/companies/_map_companies.html.haml
#map

:javascript

  $(function() {

      var markers = #{raw markers.to_json}
      mapCenter = {lat: 59.3293235, lng: 18.0685808}; // default center: Stockholm: [59.32932349999999, 18.0685808]

      if (markers.length == 1) {
        mapCenter = {lat: markers[0].latitude, lng: markers[0].longitude};
        }

      initCenteredMap(mapCenter, markers, null);

    });

app/views/companies/_search_form.html.haml
= search_form_for @search_params, method: :get, url: companies_path,
                  remote: true, id: 'companies_search' do |f|
  .form-row
    .col-sm.form-group
      = f.label :business_categories_id_in,
                "#{t('activerecord.models.business_category.one')}"
      = f.collection_select :business_categories_id_in,
                      BusinessCategory.category_and_subcategory_names,
                      :id, :full_ancestry_name, { include_blank: false },
                      { multiple: true, size: 5, style: 'width: 100%;',
                        class: 'form-control search_field',
                        data: {language: language } }
    .col-sm.form-group
      = f.label :name_in,
                "#{t('activerecord.models.company.one')}"
      = f.collection_select :name_in,
                      all_companies.order(:name),
                      :name, :name, { include_blank: false },
                      { multiple: true, size: 5, style: 'width: 100%;',
                        class: 'form-control search_field',
                        data: {language: language } }
  .form-row
    .col-sm.form-group
      = f.label :addresses_region_id_in,
                "#{t('activerecord.attributes.address.region')}"
      = f.collection_select :addresses_region_id_in,
                      Region.all,
                      :id, :name, { include_blank: false },
                      { multiple: true, size: 5, style: 'width: 100%;',
                        class: 'form-control search_field',
                        data: {language: language } }

    .col-sm.form-group
      = f.label :addresses_kommun_id_in,
                "#{t('activerecord.attributes.address.kommun')}"
      = f.collection_select :addresses_kommun_id_in,
                     Kommun.all,
                     :id, :name, { include_blank: false },
                     { multiple: true, size: 5, style: 'width: 100%;',
                       class: 'form-control search_field',
                       data: {language: language } }
    .col-sm.form-group
      = f.label :addresses_city_matches_any,
                "#{t('activerecord.attributes.address.city')}"
      = f.collection_select :addresses_city_matches_any,
                     addr_cities_select_list, :itself, :itself,
                     { include_blank: false },
                     { multiple: true, size: 5, style: 'width: 100%;',
                       class: 'form-control search_field',
                       data: {language: language } }
  .form-row
    .col-sm.d-flex.align-items-baseline
      = f.submit "#{t('search')}", class: 'btn btn-block btn-primary mt-auto p-2'

app/views/companies/show.html.haml
- content_for :head_content do
  = Adapters::CompanyToSchemaLocalBusiness.new(@company, url: company_url(@company)).as_target.to_ld_json.html_safe


%div{ id: "#{unique_css_id(@company)}",
      class: "#{item_view_class(@company, controller.action_name)}" }

  - if policy(@company).view_complete_status?
    - complete_status_css = @company.information_complete? ? 'complete' : 'not-complete'

  %header.entry-header
    .row.header
      .col.header{class: complete_status_css}
        = content_title(company_display_name(@company), user: current_user, classes: [complete_status_css])

  .entry-content.container

    - if policy(@company).view_complete_status?
      .row.complete-status
        - if @company.information_complete?
          .col
            %p.info-is-complete-text=t('.info_is_complete')
        - else
          .col
            .alert.alert-danger{ role: 'alert' }
              %p.alert-heading.info-is-not-complete-text=t('.info_is_not_complete')
              %p= t('.this_info_missing')
              %ul.missing-info
                - @company.missing_information.each do |missing_info|
                  %li=missing_info

              %p.info-is-not-complete-explanation=t('.info_is_not_complete_explanation')

    - if current_user.admin?
      .row.db-id.admin-only
        .col.db-id
          = field_or_none 'db id', @company.id, tag_options: {class: 'db-id'}

    .row
      .col
        - if @company.current_categories.any?
          .categories
            = render 'business_categories/as_list', categories: @company.current_categories

        - if payment_visible_for_user?(current_user, @company)
          %hr
            .branding-license
              %h3.section-title= t('.hbrand_fee')
              .section
                = render partial: 'branding_term_status', locals: { company: @company }
          %hr

    .row
      .col.company-story
        != @company.description
      %hr

    .row
      .col-md-5
        = field_or_none t('.name'),@company.name, tag_options: {class: 'hidden', id: 'location-text'}

        - if current_user.admin?
          = field_or_none t('.org_nr'), @company.company_number, tag_options: {class: 'company-number'}

        = field_or_none t('.phone_number'), @company.phone_number, tag_options: {class: 'phone-number'}

        = field_or_none t('.email'), mail_to(@company.email), tag_options: {class: 'email'}

        = field_or_none t('.website'), link_to(@company.website, sanitize(full_uri(@company)), target: '_blank'), tag_options: {class: 'website'}

        .social-media
          = icon_link(@company.facebook_url, 'facebook', 'Facebook URL', @company.facebook_url)
          = icon_link(@company.instagram_url, 'instagram', 'Instagram URL', @company.instagram_url)
          = icon_link(@company.youtube_url, 'youtube-square', 'Facebook URL', @company.youtube_url)


      .col-md-7
        - if @company.any_visible_addresses?
          = render partial: 'map_companies',
                   locals: { markers: location_and_markers_for([@company],
                   link_name: false )}

    - user_can_edit = policy(@company).update?

    = render 'current_members', company: @company, members: @current_members
    = render 'company_applicants', company: @company, applications: @applications if current_user.admin?

    = render 'company_addresses', company: @company, user_can_edit: user_can_edit

    - if user_can_edit

      = link_to "#{t('.add_address')}",
                new_company_address_path(@company),
                class: 'btn btn-info btn-sm ml-2 add-company-address'


    .row
      .col
        - if ! @company.dinkurs_company_id.blank? && ! @company.show_dinkurs_events && user_can_edit

          .dinkurs-show-not
            = t('events.show_not')

        - elsif @company.show_dinkurs_events && ! @company.dinkurs_company_id.blank?

          - if user_can_edit

            = button_to "#{t('.dinkurs_fetch_events')}",
                        fetch_from_dinkurs_company_path(@company),
                        remote: true,
                        class: 'btn btn-info btn-sm dinkurs-fetch-button float-right',
                        form_class: 'dinkurs-fetch-events',
                        data: { disable_with: "#{t('.dinkurs_fetching')}" }

          = render 'events/teaser_list', events: @events, company: @company,
                                         items_count: @items_count


    %hr
    .row
      .col.d-flex.justify-content-center
        - if user_can_edit
          = link_to "#{t('companies.edit_company')}",
                    edit_company_path(@company),
                    class: 'btn btn-light btn-sm edit-company mr-3'

        - if current_user.admin?
          = link_to "#{t('.delete')}", @company, method: :delete,
                    class:'btn btn-danger btn-sm delete-company',
                    data: { confirm: "#{t('.confirm_are_you_sure')}" }

= render('edit_branding_modal', company: @company) if current_user.admin?