config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  filter :locale

  # Override Devise::RegistrationsController so that we can do some custom things.
  devise_for :users, controllers: { registrations: 'registrations' }

  as :user do

    authenticated :user, lambda { |u| u.admin? } do

      namespace :admin_only, path: 'admin' do
        resources :master_checklists
        get  'master-checklists/max-list-position', to: 'master_checklists#max_list_position'
        post 'master-checklists/toggle-in-use', to: 'master_checklists#toggle_in_use'
        post 'master-checklists/set-to-no-longer-used/:id', to: 'master_checklists#set_to_no_longer_used',
             as: :master_checklists_set_to_no_longer_used

        get 'master-checklists/next-onebased-list-position', to: 'master_checklists#next_one_based_list_position'

        get 'payments', to: 'dashboard#payments'

        resources :master_checklist_types

        # Update membership status for all users
        get 'anvandare/update-membership-status-all', to: 'user_account#update_membership_status_all',
            as: :update_membership_status_all

      end


      # UserChecklists - that only an admin do:
      # View all the checklists for a user
      get 'admin/anvandare/:user_id/lista', to: 'user_checklists#index',
          as: 'user_checklists'

      # Export Information (CSV files)
      post 'admin/export-ansokan-csv'
      post 'admin/export-payments-csv'
      put 'admin/export-payments-covering-year-csv'

      # Route for testing Exception Notification configuration
      get "test_exception_notifications" => "application#test_exception_notifications"

      root to: 'shf_applications#index', as: :admin_root

    end
  end

  # ---------------------------------------------------------------------------
  # We're already using 'admin' as the name of a user role, so we
  # use "admin_only" here to avoid colliding with that term with the
  # namespace directories and class names.  We keep 'admin' as the path
  # for simplicity and some consistency.
  # namespace :admin_only, path: 'admin' do
  namespace :admin_only, path: 'admin' do

    resources :member_app_waiting_reasons

    get 'dashboard', to: 'dashboard#index'
    put 'dashboard_timeframe', to: 'dashboard#update_timeframe'

    put 'dashboard_show_recent_activity', to: 'dashboard#show_recent_activity'


    # AppConfiguration is a Singleton.
    # Admins only view and edit the AppConfiguration.
    # There is no need for index or destroy.
    #
    # :id is an optional parameter so that view buttons, etc., work fine
    # with the Rails conventions
    #
    # as: :..app_configuration..  is needed when the id is an optional parameter

    get 'app_configuration(/:id)/redigera', to: 'app_configuration#edit',
        as: :edit_app_configuration

    # must use the as: :put_app_configuration so that the method does not conflict with get 'app_configuration(/:id)' route (#show)
    put 'app_configuration(/:id)', to: 'app_configuration#update', as: :put_app_configuration

    get 'app_configuration(/:id)', to: 'app_configuration#show', as: :app_configuration


    get 'user_profile_edit/:id', to: 'user_profile#edit', as: :user_profile_edit
    put 'user_profile_update/:id', to: 'user_profile#update', as: :user_profile_update
    get 'user_profile_become/:id', to: 'user_profile#become', as: :become_user

    # Edit User Account
    get 'anvandare/:user_id/redigera', to: 'user_account#edit', as: :edit_user_account
    put 'anvandare/:user_id', to: 'user_account#update', as: :user_account

    # Design Guide
    get 'designguide', to: 'design_guide#show'

  end
  # ---------------------------------------------------------------------------

  get '/pages/*id', to: 'pages#show', as: :page, format: false


  scope(path_names: { new: 'ny', edit: 'redigera' }) do
    resources :business_categories, path: 'kategori' do
      get :get_edit_row, on: :member
      get :get_display_row, on: :member
    end

    resources :shf_applications, path: 'ansokan' do
      member do
        put 'remove_attachment'

        put 'update-reason-waiting', to: 'shf_applications#update_reason_waiting',
            as: 'reason_waiting'

        get 'start-review', to: 'shf_applications#show'
        post 'start-review', to: 'shf_applications#start_review'

        get 'accept', to: 'shf_applications#show'
        post 'accept', to: 'shf_applications#accept'
        get 'reject', to: 'shf_applications#show'
        post 'reject', to: 'shf_applications#reject'
        get 'need-info', to: 'shf_applications#show'
        post 'need-info', to: 'shf_applications#need_info'
        get 'cancel-need-info', to: 'shf_applications#show'
        post 'cancel-need-info', to: 'shf_applications#cancel_need_info'
        get 'need-payment', to: 'shf_applications#show'
        post 'need-payment', to: 'shf_applications#need_payment'
        get 'cancel-need-payment', to: 'shf_applications#show'
        post 'cancel-need-payment', to: 'shf_applications#cancel_need_payment'
        get 'received-payment', to: 'shf_applications#show'
        post 'received-payment', to: 'shf_applications#received_payment'

        get 'get_edit_row_business_category'
        get 'get_display_row_business_category'

        put 'business_subcategories'
      end

    end

    resources :companies, path: 'hundforetag' do
      member do
        put 'edit_payment', to: 'companies#edit_payment', as: 'edit_payment'
        post 'fetch_from_dinkurs', to: 'companies#fetch_from_dinkurs', as: 'fetch_from_dinkurs'
      end
    end


    # User Account.  Only admins can edit (see the route above for /admin)
    # Note that this sets the default id parameter to :user_id (instead of just :id)
    resources :users, path: 'anvandare', except: [:edit, :update]  do

      # this will add an :id parameter
      member do
        put 'edit_status', to: 'users#edit_status', as: 'edit_status'

        # User Payment Receipts
        get 'betalning-kvitton', to: 'users#view_payment_receipts',
            as: 'view_payment_receipts'
        get 'betalning-kvitton-ladda-ner', to: 'users#download_payment_receipts_pdf',
            as: 'download_payment_receipts_pdf'
      end

      post 'toggle_membership_package_sent', to: 'users#toggle_membership_package_sent'

      # ---------------------------------------------------
      # UserChecklist as a nested resource under User, with path '/lista' in the URI
      resources :user_checklists, only: [:show], path: 'lista' do
        get 'progress', to: 'user_checklists#show_progress'
      end


      # ---------------------------------------------------
      # Uploaded files

      # Do these 2 routes manually so that we can add the optional parameter :from_acct_pg
      # They must go before the resources :uploaded_files... statement below so that
      #  /anvandare/:user_id/filer/ny is matched to the request before
      #  /anvandare/:user_id/filer/:id  otherwise the router will think that :id = 'ny'
      #
      get 'filer/ny(/:from_acct_pg)', to: 'uploaded_files#new',
          as: 'new_uploaded_file'
      post 'filer/(/:from_acct_pg)', to: 'uploaded_files#create'

      # UploadedFile as a nested resource under User, with page '/filer' in the URI
      resources :uploaded_files, path: 'filer', except: [:new, :create]

    end

    # UserChecklists
    post 'anvandare/lista/all_changed_by_completion_toggle/:id', to: 'user_checklists#all_changed_by_completion_toggle',
         as: 'user_checklist_all_changed_by_completion_toggle'
    post 'anvandare/lista/set-all-completed/:id', to: 'user_checklists#set_complete_including_kids',
         as: 'user_checklist_set_complete_including_kids'
    post 'anvandare/lista/set-all-uncompleted/:id', to: 'user_checklists#set_uncomplete_including_kids',
         as: 'user_checklist_set_uncomplete_including_kids'


    get 'anvandare/:id/proof_of_membership', to: 'users#proof_of_membership',
        as: 'proof_of_membership'

    get 'hundforetag/:id/company_h_brand', to: 'companies#company_h_brand',
        as: 'company_h_brand'

    resources :shf_documents, path: 'dokument'

    get 'dokument/innehall/:page',
      to: 'shf_documents#contents_show', as: 'contents_show'

    get 'dokument/innehall/:page/redigera',
      to: 'shf_documents#contents_edit', as: 'contents_edit'

    patch 'dokument/innehall/:page',
      to: 'shf_documents#contents_update', as: 'contents_update'

    get 'medlemssidor', to: 'shf_documents#minutes_and_static_pages',
                        as: 'member_pages'
  end

  # We are not using nested resource statements for the following routes
  # because that did not seem to work when used in combination with "path:" option

  # ------- Payment as a nested resource within user --------
  post 'anvandare/:user_id/betalning/:type', to: 'payments#create',
       as: :payments

  get 'anvandare/:user_id/betalning/:id', to: 'payments#confirmation',
      as: :payment_confirmation

  post 'anvandare/betalning/klarna_push', to: 'payments#klarna_push',
       as: :payment_klarna_push
  # ----------------------------------------------------------

  # ------- Address as a nested resource within company -----
  post 'hundforetag/:company_id/adresser/:id/set_type', to: 'addresses#set_address_type',
       as: :company_address_type  # Used only for XHR action, not visible to user

  get 'hundforetag/:company_id/ny', to: 'addresses#new', as: :new_company_address

  post 'hundforetag/:company_id/adresser', to: 'addresses#create',
       as: :company_addresses

  get 'hundforetag/:company_id/adresser/:id/redigera', to: 'addresses#edit',
       as: :edit_company_address

  put 'hundforetag/:company_id/adresser/:id', to: 'addresses#update',
       as: :company_address

  delete 'hundforetag/:company_id/adresser/:id', to: 'addresses#destroy',
         as: :company_address_delete
  # ----------------------------------------------------------

app/models/shf_document.rb
# This is a document that is uploaded by a SHF user
# (see the Controller for the Policy [rules for access]).
#
# For example, an Admin might upload SHF board meeting minutes so that
#  SHF members can view it.  The SHF board meeting minutes are a ShfDocument.
#

class ShfDocument < ApplicationRecord

  belongs_to :uploader, class_name: 'User'

  has_attached_file :actual_file
  validates_attachment :actual_file, content_type: {content_type: ['image/jpeg',
                                                                   'image/gif',
                                                                   'image/png',
                                                                   'text/plain',
                                                                   'text/rtf',
                                                                   'application/pdf',
                                                                   'application/msword',
                                                                   'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                                                                   'application/vnd.ms-word.document.macroEnabled.12'],
                                                    message: I18n.t('shf_documents.invalid_upload_type')},
                       size: { in: 0..5.megabytes,
                               message: :file_too_large
                       }

=begin

  If the size validation fails, then the error message is looked up in the
  locale file(s) starting based on I18n conventions, then adding 'actual_file_'
  as the attribute, and finally adding 'file_too_large' which is what is specified by the
  'message' key within the 'size' hash above.  For some reason, the Paperclip gem will
  raise (or find) 2 error messages:  the one for 'actual_file_file_size' and
  one for 'actual_file'.

  Here's an example of the error messages in the en.yml locale file:

  en:
    errors:
      models:
        shf_document:
          attributes:
            actual_file_file_size:
              file_too_large: 'The uploaded file is too big.'
            actual_file:
              file_too_large: 'The uploaded file size must be smaller than %{max}. (Your file is %{value} bytes.)'


  Paperclip makes some instance variables available to you so that you can use them
  in the error messages if you want.  These variables are made available by the
  size validator:  Paperclip::Validators::AttachmentSizeValidator.  Specifically,
  the 'validate_each' method adds the instance variables :min, :max, and :count
  available and passes them to the error messages.  You can choose to
  use them in the messages (in the locale .yml files) or not.

    min = the lower bound of the file size
    max = the upper bound of the file size
    count = the upper bound, converted to 'human_size' by ActiveSupport::NumberHelper.number_to_human_size(size)
    value = the actual size of the file

=end

end

app/controllers/shf_documents_controller.rb
class ShfDocumentsController < ApplicationController

  include RobotsMetaTagShowActionOnly

  before_action :set_shf_document, only:  [ :show, :edit, :update, :destroy ]
  before_action :authorize_shf_doc, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_shf_doc_class,
                  only: [:index, :new, :create,
                         :contents_show, :contents_edit, :contents_update]


  def index
    @ransack_query_results = ShfDocument.ransack(params[:q])
    @shf_documents = @ransack_query_results.result(distinct: true)
  end


  def show
  end


  def new
    @shf_document = ShfDocument.new
    @shf_document.uploader = @current_user
  end


  def edit
  end


  def create
    @shf_document = ShfDocument.new(shf_document_params)

    if @shf_document.save
      redirect_to @shf_document, notice: t('.success', document_title: @shf_document.title)
    else
      helpers.flash_message(:error, t('.error', document_title: @shf_document.title ))
      render :new
    end

  end


  def update

    if @shf_document.update(shf_document_params)
      redirect_to @shf_document, notice: t('.success', document_title: @shf_document.title )
    else
      render :edit, notice: t('.error', document_title: @shf_document.title )
    end

  end


  def destroy

    @shf_document.destroy

    redirect_to shf_documents_url, notice: t('.success', document_title: @shf_document.title )

  end


  def minutes_and_static_pages
  end

  def contents_show
    page_and_page_contents
  end

  def contents_edit
    Ckeditor::Picture.images_category = 'member_pages'
    Ckeditor::Picture.for_company_id = nil

    page_and_page_contents
  end

  def contents_update
    page, file_path = page_and_file_path

    contents = params[:contents]
    File.open(file_path, 'w') do |file|
      file.write(contents)
    end

    member_page = MemberPage.find_by filename: page
    member_page.update_attribute(:title, params[:title])

    redirect_to contents_show_path(page),
                notice: t('.success', document_title: member_page.title)

  rescue => e
    helpers.flash_message(:alert,
                          t('shf_documents.contents_access_error',
                            message: e.message))
    redirect_to member_pages_path
  end


  private

  def page_and_file_path
    page = params[:page]

    file_path = page_path(page) + '.html'

    file_path.sub!('/en/', '') # strip locale prefix if present

    [ page, File.join(Rails.root, 'app', 'views', file_path) ]
  end

  def page_and_page_contents
    @page, file_path = page_and_file_path
    @contents = File.new(file_path).read
    @title = MemberPage.title(@page)
  rescue => e
    helpers.flash_message(:alert,
                          t('shf_documents.contents_access_error',
                            message: e.message))
    redirect_to member_pages_path
  end

  def authorize_shf_doc_class
    authorize ShfDocument
  end


  def authorize_shf_doc
    authorize @shf_document
  end


  # Use callbacks to share common setup or constraints between actions.
  def set_shf_document
    @shf_document = ShfDocument.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def shf_document_params
    params.require(:shf_document).permit(:uploader_id,
                                         :title,
                                         :description,
                                         :actual_file,
                                         :actual_file_file_name,
                                         :actual_file_file_size,
                                         :actual_file_content_type,
                                         :actual_file_updated_at,
                                         :_destroy,
                                         :page
    )
  end


end

app/views/shf_documents/_contents_form.html.haml
= form_tag({ controller: 'shf_documents', action: 'contents_update', page: @page },
           { method: 'patch' }) do
  .form-group
    = label_tag :title, t('.member_page_title')
    = text_field_tag :title, @title, class: 'form-control'
  .form-group
    = label_tag :contents, t('.member_page_contents')
    = cktext_area_tag :contents, @contents, class: 'form-control'

  .actions
    = submit_tag t('submit'), class: 'btn btn-primary mb-2 form-control'

app/views/shf_documents/_documents_list.html.haml
%ul{ class: ul_class }

  %li{ class: li_class }
    = link_to t('menus.nav.members.shf_meeting_minutes'), shf_documents_path

  - HighVoltage.page_ids.each do |page|
    %li{ class: li_class }
      = link_to MemberPage.title(page), contents_show_path(page: page)

app/views/shf_documents/_form.html.haml
= form_for @shf_document do |f|

  != model_errors_helper(@shf_document)

  .form-group
    = f.label :title
    = f.text_field :title,  class: 'form-control'

  .form-group
    = f.label :description
    = f.text_area :description,  class: 'form-control'


  .form-group
    = f.label :uploader_id, "#{t('shf_documents.edit.uploaded_by')}"
    %br/
    = f.collection_select(:uploader_id,[@shf_document.uploader], :id, :email)


  %p= t('shf_documents.edit.upload_the_document')

  = f.file_field 'actual_file', multiple: false, name: 'shf_document[actual_file]', class: 'btn btn-light mb-3'


  .actions
    = f.submit t('submit'), class: 'btn btn-primary mb-2 form-control'

app/views/shf_documents/contents_edit.html.haml
- content_for :javascript_for_view do
  = javascript_include_tag Ckeditor.cdn_url

%header.entry-header
  = content_title(t('.page_title', document_title: @page), user: current_user)

.entry-content
  = render 'contents_form'

%hr
.text-center
  = link_to t('cancel'), contents_show_path(@page),
      class: 'btn btn-light btn-sm shf-document-view'

  = link_to t('menus.nav.members.member_pages'), member_pages_path,
      class: 'btn btn-light btn-sm shf-document-view'

app/views/shf_documents/contents_show.html.haml
.shf-document.show#shf-document

  %header.entry-header
    = content_title(@title, user: current_user)
  .entry-content
    - if policy(ShfDocument).contents_update?
      = link_to "#{t('.edit_member_page')}",
                contents_edit_path(page: @page),
                class: 'btn btn-light edit-member-page'

    != @contents

app/views/shf_documents/edit.html.haml
%header.entry-header
  = content_title(t('.page_title', document_title: @shf_document.title))

.entry-content
  = render 'form'

%hr
.text-center
  = link_to "#{t('shf_documents.view_shf_document')}", @shf_document, class: 'btn btn-light btn-sm shf-document-view'

  = link_to "#{t('shf_documents.all_shf_documents')}", shf_documents_path, class: 'btn btn-light btn-sm shf-document-all'

app/views/shf_documents/index.html.haml
%header.entry-header
  = content_title(t('.page_title'), user: current_user)

.entry-content

  %p= t('.instructions')

  %table.table.table-hover.table-sm#shf-documents
    %thead
      %tr
        %th= sort_link(@ransack_query_results, :title, t('.title'))

        %th= sort_link(@ransack_query_results, :description, t('.description'))

        - if current_user.admin?
          %th
          %th

    %tbody
      - @shf_documents.each do |shf_document|
        %tr.shf-document
          %td.title= link_to shf_document.title, shf_document.actual_file.url, target: "_blank", id: "shf-document-link-#{shf_document.id}", class: "shf-document-file-link"

          %td.description= shf_document.description

          - if current_user.admin?
            %td= link_to t('.view_details'), shf_document
            %td= link_to t('delete'), shf_document, :method => :delete, :data => { :confirm => t('.delete_confirm', document_title: shf_document.title) }

  - if current_user.admin?
    %br
    .center
      = link_to t('shf_documents.new_shf_minutes'), new_shf_document_path, class: 'btn btn-primary btn-shf-document-new'

app/views/shf_documents/minutes_and_static_pages.html.haml
%header.entry-header
  = content_title(t('.member_pages'), user: current_user)

.entry-content
  = render partial: 'documents_list', locals: { ul_class: '', li_class: '' }

app/views/shf_documents/new.html.haml
.shf-document.new#shf-document-new

  %header.entry-header
    = content_title(t('.page_title'), user: current_user)

  .entry-content

    = render 'form'

  %hr
  .text-center
    = link_to "#{t('shf_documents.all_shf_minutes')}", shf_documents_path, class: 'btn btn-light btn-sm btn-shf-documents-all'

app/views/shf_documents/show.html.haml
-# div{ :id => "#{unique_css_id(@shf_document)}", class: "#{item_view_class(@shf_document, controller.action_name)}" }
.shf-document.show#shf-document

  %header.entry-header
    = content_title(@shf_document.title, user: current_user)

  .entry-content

    = field_or_none t('.title'), @shf_document.title, tag_options: {class: 'shf-document-title'}

    = field_or_none t('.description'), @shf_document.description, tag_options: {class: 'shf-document-description'}

    = field_or_none t('.uploaded_by'), @shf_document.uploader.email, tag_options: {class: 'shf-document-uploader'}

    = field_or_none t('.uploaded_on'), @shf_document.created_at, tag_options: {class: 'shf-document-uploaded-on'}
    %p
      = t('.filename')
      = link_to @shf_document.actual_file_file_name, @shf_document.actual_file.url, target: "_blank", id: "shf-document-link-#{@shf_document.id}", class: "shf-document-file-link"

    %hr
    .text-center
      - if policy(@shf_document).update?
        = link_to "#{t('shf_documents.edit_shf_document')}", edit_shf_document_path(@shf_document), class: 'btn btn-light btn-sm edit-member-page'

      - if policy(@shf_document).index?
        = link_to "#{t('shf_documents.all_shf_documents')}", shf_documents_path, class: 'btn btn-light btn-sm all-shf-documents'

      - if policy(@shf_document).destroy?
        = link_to "#{t('delete')}", @shf_document, method: :delete, class:'btn btn-danger btn-sm delete-shf-document', data: { confirm: "#{t('.delete_confirm', document_title: @shf_document.title)}" }